### ISSUE TITLE
Converting this starter to theme

### ISSUE THREAD

**Issue by lamLeX** [eduard-kirilov/gatsby-ts-apollo-starter#1]
I really love this starter.

Is there any chance that you can convert this starter into theme?
https://www.gatsbyjs.com/docs/themes/converting-a-starter/

**Comment by eduard-kirilov** [comment]
Hi, thank you for your question.

As soon as I have free time, I plan to refactor this starter, and possibly convert this starter into a theme.

Sincerely,
Eduard.
